---
title: "Sysnav"
date: 2017-12-04T15:18:06Z
draft: false
---

* Abstract

A vast array of modern technologies has come to rely on precise
geolocalization, particularly in the transport industry. However,
existing technologies based on the GPS cannot be applied directly to
pedestrian navigation. GPS resolution is limited to a few meters in
best-case scenarios and depends on permanent satellite
communication. Of these two restrictions, the former renders GPS
nearly useless for pedestrian navigation in urban environments, while
the latter excludes common scenarios where radio communications are
unavailable, such as buildings and tunnels.

The widespread adoption of inertial data sensors (acceleration and
angular speed) through the development of smartphones and other
connected devices leads to a new navigation approach using only this
data, that do not require any external communication. This project
uses statistical and algorithmic methods to render a trajectory in
real-time on a foot-mounted embedded device. Traditional navigation
methods such as Kalman filtering are combined with machine learning
and optimization to get a precision smaller than a metre. The
resulting trajectory is able to distinguish individual steps in
complex situations like staircases and jumps.

[[sysnav_internship.pdf][Outline of the confidential report (PDF, in French)]] and [[https://dlozeve.github.io/stage3a/][slides]]
